name = "HorizonSideRobots"
uuid = "d5e94110-5307-4c9c-bf91-3c01b52f9d89"
version = "0.4.0"
authors = ["Виктор Федоров <fdorov@mail.ru>"]

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
Makie = "0.24.13"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
